services:
  postgres:
    image: postgres:16
    container_name: quickbite-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: quickbite
      POSTGRES_PASSWORD: quickbite_dev_pass
      POSTGRES_DB: quickbite_users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:7
    container_name: quickbite_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: quickbite
      MONGO_INITDB_ROOT_PASSWORD: quickbite_dev_pass 
    volumes:
      - mongodata:/data/db    

volumes:
  postgres_data:
  mongodata: